apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: passage
  labels:
    app: minio

spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio

  template:
    metadata:
      name: minio
      labels:
        app: minio

    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2021-12-20T22-07-16Z
          imagePullPolicy: IfNotPresent

          env:
            - name: MINIO_ROOT_USER
              value: "passage"
            - name: MINIO_ROOT_PASSWORD
              value: "passage123"

          command: ["sh", "-c", "mkdir -p /data/passage && minio server --address \":9079\" --console-address \":9080\" /data"]

          volumeMounts:
            - mountPath: /data
              name: data


      volumes:
        - name: data
          hostPath:
            path: /tmp/minio-storage

      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  namespace: passage
  name: minio

spec:
  selector:
    app: minio
  type: ClusterIP

  ports:
    - name: "console"
      protocol: TCP
      port: 80
      targetPort: 9080

    - name: "api"
      protocol: TCP
      port: 9079
      targetPort: 9079
