ALTER TABLE reverse_tunnels
    DROP COLUMN ssh_port,
    DROP COLUMN service_port,

    ADD COLUMN ssh_port INTEGER GENERATED ALWAYS AS IDENTITY (MINVALUE 49152 MAXVALUE 57343) UNIQUE,
    ADD COLUMN service_port INTEGER GENERATED ALWAYS AS IDENTITY (MINVALUE 57344 MAXVALUE 65535) UNIQUE
;

ALTER TABLE reverse_tunnels DROP COLUMN id;
ALTER TABLE reverse_tunnels ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE reverse_tunnels DROP COLUMN private_key;
