// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tunnel.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTunnel = `-- name: GetTunnel :one
SELECT id, created_at, enabled, sshd_port, tunnel_port, last_used_at, error FROM passage.reverse_tunnels WHERE id = $1
`

func (q *Queries) GetTunnel(ctx context.Context, id pgtype.UUID) (PassageReverseTunnel, error) {
	row := q.db.QueryRow(ctx, getTunnel, id)
	var i PassageReverseTunnel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Enabled,
		&i.SshdPort,
		&i.TunnelPort,
		&i.LastUsedAt,
		&i.Error,
	)
	return i, err
}
