apiVersion: v1
kind: Namespace
metadata:
  name: stats
  labels:
    name: stats

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stats
  name: statsd-exporter
  labels:
    app: statsd-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statsd-exporter
  template:
    metadata:
      name: statsd-exporter
      labels:
        app: statsd-exporter
    spec:
      restartPolicy: Always

      containers:
        - name: statsd-exporter
          image: prom/statsd-exporter:latest
          imagePullPolicy: IfNotPresent

          args: ["--log.level=debug"]

---

apiVersion: v1
kind: Service
metadata:
  namespace: stats
  name: statsd-exporter
spec:
  selector:
    app: statsd-exporter
  type: ClusterIP
  ports:
    - name: "prometheus"
      port: 9102
      targetPort: 9102
    - name: "statsd"
      port: 9125
      targetPort: 9125
    - name: "statsd-udp"
      port: 9125
      targetPort: 9125
      protocol: "UDP"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stats
  name: prometheus
  labels:
    app: prometheus

spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      restartPolicy: Always

      containers:
        - name: prometheus
          image: prom/prometheus:latest
          imagePullPolicy: IfNotPresent

          args:
            - "--config.file=/prometheus.yml"
            - "--log.level=debug"
            - "--web.listen-address=:9090"

          volumeMounts:
            - name: config
              subPath: prometheus.yml
              mountPath: /prometheus.yml

      volumes:
        - name: config
          configMap:
            name: prometheus

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stats
  name: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval:      15s
      evaluation_interval:  15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'exporter'
        static_configs:
          - targets: ['statsd-exporter:9102']
            

---

apiVersion: v1
kind: Service
metadata:
  namespace: stats
  name: prometheus
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
    - name: "http"
      port: 9090
      targetPort: 9090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stats
  name: grafana
  labels:
    app: grafana

spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      restartPolicy: Always

      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - name: config
              subPath: config.ini
              mountPath: /etc/grafana/grafana.ini
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/

      volumes:
        - name: config
          configMap:
            name: grafana-config
        - name: datasources
          configMap:
            name: grafana-datasources

---

apiVersion: v1
kind: Service
metadata:
  namespace: stats
  name: grafana
spec:
  selector:
    app: grafana
  type: ClusterIP
  ports:
    - name: "http"
      port: 80
      targetPort: 3000

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stats
  name: grafana-config
data:
  config.ini: |
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Admin 
---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stats
  name: grafana-datasources
data:
  prometheus.yaml: |
    apiVersion: 1
 
    datasources:
      - uid: prometheus
        type: prometheus
        name: Prometheus 
        access: proxy 
        url: http://prometheus:9090
        isDefault: true
        editable: true