BEGIN;

CREATE TABLE IF NOT EXISTS tunnels(
  id VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  public_key TEXT NOT NULL,
  private_key TEXT NOT NULL,
  port INTEGER NOT NULL,
  server_endpoint TEXT NOT NULL,
  server_port INTEGER NOT NULL,
  service_endpoint TEXT NOT NULL,
  service_port INTEGER NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reverse_tunnels(
  id VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  public_key TEXT NOT NULL,
  private_key TEXT NOT NULL,
  port INTEGER NOT NULL,
  ssh_port INTEGER NOT NULL,
  PRIMARY KEY (id)
);

COMMIT;
