BEGIN;

CREATE TABLE IF NOT EXISTS tunnels(
  id VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type VARCHAR(128) NOT NULL,
  public_key TEXT NOT NULL,
  private_key TEXT NOT NULL,
  port INTEGER NOT NULL,
  PRIMARY KEY (id)
);

COMMIT;
